version: "3"
services:
  site:
    command: jekyll serve --host 0.0.0.0
    image: jekyll/jekyll:latest
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=env
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      - 80:4000
